[package]
name = "zappy-ai"
edition = "2024"
publish = false

[dependencies]
tokio = { version = "1", features = ["net", "macros", "rt", "time", "io-util", "sync", "parking_lot"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
parking_lot = "0.12"
